spring.application.name=usermanagementsystem

spring.datasource.url=jdbc:mysql://localhost:3306/users_management
spring.datasource.username=root
spring.datasource.password=JESUSglory_7
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=1010

#jwt.secret=mySuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
#jwt.expiration=36000000
